# Generated by Django 4.2 on 2023-04-28 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
            primary_key=True, serialize=False, verbose_name='ID')),
                ('ParkingName', models.CharField(max_length=100)),
                ('OwnerName', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('ContactNo', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('UserName', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('ParkingFee', models.IntegerField(max_length=10)),
                ('Status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'parkinginfo',
            },
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
         primary_key=True, serialize=False, verbose_name='ID')),
                ('SpaceName', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('ParkingID', models.ForeignKey(
      null=True, on_delete=django.db.models.deletion.SET_NULL,
    to='parking.parkinginfo')),
            ],
            options={
                'db_table': 'parkingspace',
            },
        ),
        migrations.CreateModel(
            name='BookSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('SpaceName', models.CharField(max_length=100)),
                ('BookDate', models.CharField(max_length=100)),
                ('BookTime', models.CharField(max_length=100)),
                ('PaymentMode', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Mobile', models.CharField(max_length=100)),
                ('CardHolderName', models.CharField(max_length=100)),
                ('CardNo', models.CharField(max_length=100)),
                ('CVV', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('ParkingID', models.ForeignKey(
         null=True, on_delete=django.db.models.deletion.SET_NULL, 
         to='parking.parkinginfo')),
                ('bookedby', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, 
                    to='signup.signup')),
            ],
            options={
                'db_table': 'bookspace',
            },
        ),
    ]
