# Generated by Django 4.2 on 2023-04-28 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'parkinglocation',
            },
        ),
        migrations.AddField(
            model_name='parkinginfo',
            name='LocationID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.parkinglocation'),
        ),
    ]
