# Generated by Django 4.2 on 2023-04-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parkinglocation_parkinginfo_locationid'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='Status',
            field=models.CharField(default='Available', max_length=100, null=True),
        ),
    ]
