# Generated by Django 4.2 on 2023-04-30 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_parkingspace_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookspace',
            name='ParkingID',
        ),
        migrations.RemoveField(
            model_name='bookspace',
            name='SpaceName',
        ),
        migrations.AddField(
            model_name='bookspace',
            name='SpaceID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.parkingspace'),
        ),
    ]
