# Generated by Django 4.2 on 2023-04-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_remove_signup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Gender',
            field=models.CharField(max_length=10),
        ),
    ]
